# Generated by Django 3.0.7 on 2020-06-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trucks',
            name='next_service',
            field=models.DateField(auto_now_add=True, verbose_name='Next Service Date'),
        ),
    ]
