# Generated by Django 3.0.7 on 2020-06-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_auto_20200621_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trucks',
            name='next_service',
            field=models.DateField(verbose_name='Next Service Date'),
        ),
    ]
