# Generated by Django 3.0.7 on 2020-06-20 18:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vin', models.CharField(default=None, max_length=17)),
                ('current_mileage', models.IntegerField(null=True)),
                ('make', models.CharField(choices=[('ACURA', 'Acura'), ('BMW', 'BMW'), ('CHEVROLET', 'Chevrolet'), ('DODGE', 'Dodge'), ('FORD', 'Ford'), ('GMC', 'GMC'), ('HONDA', 'Honda')], default='Acura', max_length=20)),
                ('model', models.CharField(choices=[('Acura', (('ILX', 'ILX'), ('MDX', 'MDX'), ('RDX', 'RDX'))), ('BMW', (('128', '128'), ('228', '228'), ('530', '530')))], default=None, max_length=20)),
                ('seats', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default='2', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
