# Generated by Django 3.0.7 on 2020-06-18 01:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vin', models.CharField(default='VIN NUMBER', max_length=17)),
                ('current_mileage', models.IntegerField(null=True)),
            ],
        ),
    ]
