# Generated by Django 3.0.7 on 2020-06-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='service_interval',
            field=models.CharField(choices=[('3 Months', '3 Months'), ('6 Months', '6 Months'), ('8 Months', '8 Months'), ('12 Months', '12 Months')], default='3 Months', max_length=12),
        ),
        migrations.AlterField(
            model_name='cars',
            name='make',
            field=models.CharField(choices=[('ACURA', 'Acura'), ('BMW', 'BMW'), ('CHEVROLET', 'Chevrolet'), ('DODGE', 'Dodge'), ('FORD', 'Ford'), ('HONDA', 'Honda')], default='Acura', max_length=20),
        ),
        migrations.AlterField(
            model_name='cars',
            name='model',
            field=models.CharField(choices=[('Acura', (('ILX', 'ILX'), ('MDX', 'MDX'), ('RDX', 'RDX'))), ('BMW', (('128', '128'), ('228', '228'), ('530', '530'))), ('Chevrolet', (('Aveo', 'Aveo'), ('Impala', 'Impala'), ('Malibu', 'Malibu'))), ('Dodge', (('Avenger', 'Avenger'), ('Challenger', 'Challenger'), ('Dart', 'Dart'))), ('Honda', (('Accord', 'Accord'), ('Fit', 'Fit'), ('Insight', 'Insight')))], default=None, max_length=20),
        ),
    ]
