# Generated by Django 3.0.7 on 2020-06-21 05:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoatLengthChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BoatMakeChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BoatModelChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Boats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hin', models.CharField(default=None, max_length=12, verbose_name='HIN')),
                ('current_hours', models.IntegerField(null=True)),
                ('year', models.IntegerField(default=None)),
                ('make', models.CharField(choices=[('CAYMAS BOATS', 'Caymas Boats'), ('NORTHWEST BOATS', 'Northwest Boats'), ('GRIZZLY', 'Grizzly')], default='Caymas Boats', max_length=15)),
                ('model', models.CharField(choices=[('Caymas Boats', (('26HB', '26HB'), ('CX 18 C', 'CX 18 S'), ('CX 20', 'CX 20'))), ('Northwest Boats', (('22 SIGNATURE', '22 Signature'), ('206 FREEDOM', '206 Freedom'), ('218 NORTHSTAR', '218 Northstar'))), ('Grizzly', (('1448 JON', '1448 Jon'), ('1648 JON', '1648 Jon'), ('1754 JON', '1754 Jon')))], default=None, max_length=15)),
                ('length', models.CharField(choices=[('14FT', '14ft'), ('16FT', '16ft'), ('18FT', '18ft'), ('20FT', '20ft'), ('25FT', '25ft'), ('30FT', '30ft')], default='14ft', max_length=4)),
                ('width', models.CharField(choices=[('60IN', '60in'), ('70IN', '70in'), ('80IN', '80in'), ('90IN', '90IN')], default='60in', max_length=4)),
                ('service_interval', models.CharField(choices=[('6 Months', '6 Months'), ('12 Months', '12 Months'), ('18 Months', '18 Months'), ('24 Months', '24 Months')], default='6 Months', max_length=10)),
                ('next_service', models.DateField(verbose_name='Next Service Date')),
            ],
            options={
                'verbose_name_plural': 'Boats',
            },
        ),
        migrations.CreateModel(
            name='BoatServiceInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BoatWidthChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
